//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaloWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaunanTila
    {
        public int SaunanTilaID { get; set; }
        public Nullable<int> SaunaID { get; set; }
        public string SaunanTila1 { get; set; }
        public string SaunanLampotila { get; set; }
        public Nullable<System.DateTime> PVM { get; set; }
    
        public virtual Saunat Saunat { get; set; }
    }
}
