//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaloWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talot
    {
        
        

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Talot()
        {
            this.TalonTila = new HashSet<TalonTila>();
        }
    
        public int TaloID { get; set; }
        public string TalonSijainti { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TalonTila> TalonTila { get; set; }
        
    }
}
